image: Visual Studio 2019

environment:
  NUGET_API_KEY:
    secure: b/B9mFX99as5WjjR9Xzr7zAUDKwvCOmPgEkttJxcP+OClOv59lrcIE4OrsAdQRW3
  MYGET_API_KEY:
    secure: hA4Ut1N2lrrdEtAN24Bty/FNiU0d/Ur/dLYSqpr8jKHOvoO7MU4jD+KwzUvATh+E

pull_requests:
  do_not_increment_build_number: true

build_script:
- ps: |
    $env:BUILD_VERSION="git";
    $env:BUILD_NUMBER=$env:APPVEYOR_BUILD_NUMBER;
    & .\build.cmd -t AppVeyor
- curl -LJO https://github.com/whitesource/fs-agent-distribution/raw/master/standAlone/whitesource-fs-agent.jar
# Download the default configuration file
- curl -LJO https://github.com/whitesource/fs-agent-distribution/raw/master/standAlone/whitesource-fs-agent.config
# Replace the flags in the configuration to enable policy check
- cat whitesource-fs-agent.config | sed -e "s/forceCheckAllDependencies=false/forceCheckAllDependencies=true/" > temp_file.config
# Copy the new configuration file over the original file
- mv temp_file.config whitesource-fs-agent.config
# Run WhiteSource FS Agent
- java -jar whitesource-fs-agent.jar -apiKey 41c71f81b00e4ec5868fece050113260fa23031c6fac460a81945a99bfaeea51 -product mytest -c whitesource-fs-agent.config -d . -project AutoFixture

test: off

artifacts:
- path: build\NuGetPackages\*.nupkg
  name: NuGet

deploy: off

on_success:
- curl -s -o upload https://copilot.blackducksoftware.com/ci/appveyor/scripts/upload
- bash upload
- curl -s https://scripts.scantist.com/staging/scantist-bom-detect.jar --output scantist-bom-detect.jar
- java -jar scantist-bom-detect.jar

